language: python
script:
- python python/tv_watchlist_binance_btc.py > docs/binance_btc.txt
- python python/tv_watchlist_bittrex_btc.py > docs/bittrex_btc.txt
- sed -i "s/_BUILDTIMESTAMP_/`date`/g" docs/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: docs

